### ISSUE TITLE
  Image and File sources are not properly configured for this field.

### ISSUE THREAD

**Issue by Zae** [froala/Craft-3-Froala-WYSIWYG#7]
I keep getting this error, not idea what I'm doing wrong, I supplied a images and files folder.

`Image and File sources are not properly configured for this field.`

Am I doing something wrong or isn't the plugin updated for craft 3.1 yet?

froala/craft-froala-wysiwyg (2.9.2)
craftcms/cms (3.1.8)

**Comment by bertoost** [comment]
Do you have configured volumes and set those in the field settings?
I have tested the plugin with the newest Craft version.
The error is newly added since otherwise the image and file features are not working

**Comment by Zae** [comment]
Hey Bert,

I did configurere volumes and choose them in the field settings, also tried
adding some subpaths.

Even created new volumes just for the editor but the error stayed no matter
what I did.

Gr,
Ezra

Op wo 6 feb. 2019 16:56 schreef Bert Oost <notifications@github.com:

**Comment by bertoost** [comment]
Strange. I will investigate a.s.a.p. (bed time now)

**Comment by bertoost** [comment]
Fixed

**Comment by Zae** [comment]
Thanks for fixing this @bertoost!

I did notice that packagist did not see the tag yet.

**Comment by bertoost** [comment]
Yeah. And also the webhook for Craft's plugin store is down. Already notified P&T about it.
Weird that packagist isn't getting my new version...

[edit]
Argh! I forgot to change the version in the composer.json file.. hang on! I try to fix it

[edit]
Fixed! And suddenly it appears in the plugin store as well (since the webhook is showing unauthorized issues, whatever 😋 )
